---

- name: Install Git
  hosts: all
  become: yes

  tasks:
    - name: Install Git package
      apt:
        name: git
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Git package
      yum:
        name: git
        state: present
      when: ansible_os_family == "RedHat"